//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPanneGarageMvcWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Reparations = new HashSet<Reparation>();
        }
    
        public int Id { get; set; }
        public int CategoriesArticlesId { get; set; }
        public int TypesVehiculesId { get; set; }
        public string NomArticle { get; set; }
        public string PrixUnitaire { get; set; }
    
        public virtual CategoriesArticle CategoriesArticle { get; set; }
        public virtual TypesVehicule TypesVehicule { get; set; }
        public virtual ICollection<Reparation> Reparations { get; set; }
    }
}
