//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPanneGarageMvcWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionPanneGarageEntities : DbContext
    {
        public GestionPanneGarageEntities()
            : base("name=GestionPanneGarageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Article> Articles { get; set; }
        public DbSet<CategoriesArticle> CategoriesArticles { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<PanneVehicule> PanneVehicules { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Reparation> Reparations { get; set; }
        public DbSet<TypesVehicule> TypesVehicules { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
