//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPanneGarageMvcWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanneVehicule
    {
        public PanneVehicule()
        {
            this.Reparations = new HashSet<Reparation>();
        }
    
        public int Id { get; set; }
        public int ClientsId { get; set; }
        public string Plaque { get; set; }
        public string Marque { get; set; }
        public string Modele { get; set; }
        public System.DateTime DateEnregistrement { get; set; }
        public string EtatVehicule { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Reparation> Reparations { get; set; }
    }
}
