//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPanneGarageMvcWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesVehicule
    {
        public TypesVehicule()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int Id { get; set; }
        public string DescriptionsVehicules { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
    }
}
